server:
  port: 9094

spring:
  application:
    name: MESSAGING-SERVICE
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/message_service_backend
    username: root
    password: P@ssw0rd!@#
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ticket:
  queue:
    name: ticket_queue
  exchange:
    name: ticket_exchange
  routing:
    key: ticket_routing_key