server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_backend
    username: root
    password: P@ssw0rd!@#
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
